api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('articles', views.ArticleViewSet)
router.register('categories', views.CategoryViewSet)
router.register('products', views.ProductViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('register/', views.register_user),
]

articles/urls.py
from django.urls import path

from . import views


app_name = 'articles'
urlpatterns = [
    path('index', views.index, name='all_articles'),
    path('<int:article_id>', views.detail, name='detail'),
    path('<int:article_id>/like', views.like, name='like'),
    path('author_detail/<author_id>', views.author_detail, name='author_detail')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework_simplejwt.views import TokenVerifyView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:question_id>/results', views.results, name='results'),
    path('create', views.create_question, name='create'),

]

articles/models.py
from django.db import models
from django.contrib import admin

# Create your models here.


class Author(models.Model):
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    date_of_birth = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Article(models.Model):
    text = models.TextField(max_length=300)
    pub_date = models.DateTimeField(verbose_name="date published")
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    likes = models.IntegerField(default=0)

    @admin.display(
        boolean=True,
        description='is popular'
        # ordering='like_count'
    )
    def is_popular(self):
        return self.likes > 100

    def __str__(self):
        return self.title

articles/views.py
from random import randint

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
# Create your views here.
from .models import Article, Author
from django.utils import timezone
from datetime import datetime


def index(request):
    articles = Article.objects.all()
    context = {'all_articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, article_id: int):
    # article = get_object_or_404(Article, id=article_id)
    a = randint(1, 2)

    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404('Article does not exist')
    try:
        author = Author.objects.get(article=article)
    except Author.MultipleObjectsReturned:
        author = Author.objects.filter(article=article)

    context = {'article': article, 'author': author}
    return render(request, 'articles/detail.html', context)


def like(request, article_id: int):
    article = get_object_or_404(Article, id=article_id)
    try:
        like = Article.objects.get(id=article_id)
    except (KeyError, Article.DoesNotExist):
        return render(request, 'articles/detail.html', {
            'error_message': "i dont know",
            'article': article,
        })
    like.likes += 1
    like.save()
    return redirect('articles:detail', article.id)


def author_detail(request, author_id: id):
    author = get_object_or_404(Author, id=author_id)

    articles = Article.objects.filter(authors=author.id)
    context = {'author': author, 'articles': articles}
    return render(request, 'articles/author_detail.html', context)

articles/templates/articles/author_detail.html
{% extends 'articles/base.html' %}

{% block body %}
    <b>Author:<br></b>
<br>
First_name: {{author.first_name}}<br>
Last_name: {{author.last_name}}<br>
Date of birth: {{author.date_of_birth}}<br>
<b>Произведения автора:</b><br>
{% for i in articles %}
<a href="{% url 'articles:detail' i.id%}">{{i}}</a><br>
{%endfor%}
{% endblock %}

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}Polls APP{% endblock %}</title>
</head>
<body>
    <div class="hstack gap-3">
        <a href="{% url 'polls:index' %}">
            <img src="https://netstorage.ringcentral.com/appext/logo/kNku72HNQPWCo-uLCKS4Hw~wCZbXGy1Qu-z3dzQ3U_j7Q/b8e47126-bf75-41df-bbf0-844db0a925a4.png" height="40"/>
        </a>
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-danger"/>
            </form>
        {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
        {% endif %}
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url 'articles:all_articles'%}">Главная</a>
    {% block body %}{% endblock %}
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block title %}Article{% endblock %}

{% block body %}
      <form action="{% url 'articles:like' article.id %}" method="post">
        {% csrf_token %}
            {% if article%}
                <ul>
                    <legend><h1>Название статьи: {{ article.title }}<br></h1></legend>
                    {% if author|length > 1%}
                        {% for author in author %}
                            Автор: <a href="{% url 'articles:author_detail' author.id %}">{{ author.first_name }}</a> {{author.last_name}}<br>
                        {% endfor %}
                    {% else %}
                        Автор: <a href="{% url 'articles:author_detail' author.id %}">{{ author.first_name }}</a> {{author.last_name}}<br>
                    {% endif %}
                <i>{{ article.text }}<br></i>
                like: {{article.likes}}
            </ul>
         <input type="submit" value="like"/>

        {%else%}
            <p>No Article are available.</p>
        {%endif%}
      </form>
{% endblock %}

articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block body %}
    {% if all_articles %}
        <ul>
            {% for article in all_articles %}
            <li><a href="{% url 'articles:detail' article.id %}">{{ article.title}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No article are available</p>
    {% endif %}
{% endblock %}

articles/templates/articles/like.html
{% extends 'articles/base.html' %}

{% block title %}Article results{% endblock %}

{% block body %}
    {% if article%}
      <ul>
        <legend><h1>Название статьи: {{ article.title }}<br></h1></legend>
         Автор: {{ article.authors.first_name }}<br>
          <i>{{ article.text }}<br></i>
          like: {{article.likes}}
      </ul>
            <input type="submit" value="like"/>

    {%else%}
      <p>No Article are available.</p>
    {%endif%}
{% endblock %}