api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)
router.register('articles', views.ArticleViewSet)
router.register('categories', views.CategoryViewSet)
router.register('products', views.ProductViewSet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote),
    path('register/', views.register_user),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework_simplejwt.views import TokenVerifyView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('api/', include('api.urls')),
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.main, name='main'),
    path('products', views.products_view, name='products_view'),
    path('products/<int:product_id>', views.product_detail, name='product_detail'),
    path('categories/<category_id>', views.category, name='all_of_category'),
    path('categories', views.categories, name='all_categories'),
    path('register', views.regform, name='register'),
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('shopping_cart', views.shopping_cart, name='shopping_cart'),
    path('clear_order', views.clear_order, name='clear_order'),
    path('clear_concrete_order', views.clear_concrete_order, name='clear_concrete_order'),
    path('update_count', views.update_count, name='update_count'),
    path('make_order', views.make_order, name='make_order'),
    path('success_order', views.success_order, name='success_order'),
    path('account', views.account, name='account'),
    path('order_history', views.order_history, name='order_history'),
    path('repeat_order', views.repeat_order, name='repeat_order'),

]

shop/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class OrderEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='+')
    count = models.IntegerField(default=0)
    order = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='order')

    def total(self):
        return  f'{self.count * self.product.price}'


    def __str__(self):
        #return f'{self.product} - {self.count} - {self.count * self.product.price}'
        return f'{self.product}'


class Order(models.Model):
    class Status(models.TextChoices):
        INITIAL = 'INITIAL'
        COMPLETED = 'COMPLETED'
        DELIVERED = 'DELIVERED'

    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, related_name='orders')
    status = models.CharField(max_length=200, default=Status.INITIAL, choices=Status.choices)

    def __str__(self):
        return f"{self.profile.user.username}-{self.status}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    shopping_cart = models.OneToOneField(Order, on_delete=models.SET_NULL,
                                         null=True, blank=True, related_name='+')

    def __str__(self):
        return f'{self.user.username}'

shop/forms.py
from django import forms


class UserForm(forms.Form):
    count = forms.IntegerField()

shop/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Product, Category, Profile, Order, OrderEntry
from django.core.paginator import Paginator
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('shop/main')
        else:
            messages.info(request, 'username or password incorrect')

    context = {}
    return render(request, 'shop/login.html', context)


def regform(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created ' + user)
            return redirect('login')

    context = {'form': form}
    return render(request, 'shop/register.html', context)


def main(request):
    try:
        category = Category.objects.all()
        product = Product.objects.all()
    except Product.DoesNotExist:
        raise Http404('Product does not exist')
    context = {'products': product, 'category': category}
    return render(request, 'shop/base.html', context)


def products_view(request, ):
    contact_list = Product.objects.all()
    paginator = Paginator(contact_list, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'products': Product.objects.all(), "page_obj": page_obj}
    return render(request, 'shop/products.html', context)


def product_detail(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        raise Http404('Product does not exist')
    context = {'product': product}
    return render(request, 'shop/detail.html', context)


def category(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        raise Http404('Category does not exist')
    context = {'category': category}
    return render(request, 'shop/category.html', context)


def categories(request):
    try:
        category = Category.objects.all()
    except Category.DoesNotExist:
        raise Http404('Category does not exist')
    context = {'category': category}
    return render(request, 'shop/categories.html', context)


@login_required
def add_to_cart(request):
    if request.method == 'POST':
        product_id = request.POST['id']
        product = get_object_or_404(Product, id=product_id)
        try:
            profile = Profile.objects.get(user=request.user)
            profile.save()
        except Profile.DoesNotExist:
            profile = Profile.objects.create(user=request.user)
            profile.save()
        if not profile.shopping_cart:
            profile.shopping_cart = Order.objects.create(profile=profile)
            profile.save()
        try:
            order_entry = OrderEntry.objects.get(order=profile.shopping_cart, product=product)
        except OrderEntry.DoesNotExist:
            order_entry = OrderEntry.objects.create(order=profile.shopping_cart, product=product)
        order_entry.count += 1
        order_entry.save()
        return redirect('shop:product_detail', product_id)


@login_required(redirect_field_name='login')
def shopping_cart(request):
    try:
        profile = Profile.objects.get(user=request.user)
        profile.save()
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)
        profile.save()
    order_entry = OrderEntry.objects.filter(order=profile.shopping_cart).order_by('product')
    t = 0
    for i in OrderEntry.objects.filter(order=profile.shopping_cart):
        t += i.product.price * i.count
    context = {'order_entry': order_entry, 'total': t}

    return render(request, 'shop/shopping_cart.html', context)


def clear_order(request):
    profile = Profile.objects.get(user=request.user)
    OrderEntry.objects.filter(order=profile.shopping_cart).delete()
    return redirect('shop:shopping_cart')


def clear_concrete_order(request):
    product_id = request.POST['id']
    profile = Profile.objects.get(user=request.user)
    OrderEntry.objects.filter(order=profile.shopping_cart, product=product_id).delete()
    return redirect('shop:shopping_cart')


def update_count(request):
    if request.method == 'POST':
        count = request.POST['new']
        id = request.POST['id']
        if int(count) > 0:
            order = OrderEntry.objects.get(id=id)
            order.count = count
            order.save()
        else:
            order = OrderEntry.objects.get(id=id)
            order.delete()
    return redirect('shop:shopping_cart')


def make_order(request):
    if request.method == 'POST':
        profile = Profile.objects.get(user=request.user)
        if profile.shopping_cart.order.exists():
            profile.shopping_cart.status = 'COMPLETED'
            profile.shopping_cart.save()
            profile.shopping_cart = Order.objects.create(profile=profile)
            profile.save()
            return redirect('shop:success_order')
        else:
            return redirect('shop:shopping_cart')


@login_required(redirect_field_name='login')
def success_order(request):
    return render(request, 'shop/success_order.html')


@login_required(redirect_field_name='login')
def account(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    first_name = user.first_name
    last_name = user.last_name
    email = user.email
    if 'first_name' in request.POST:
        first_name = request.POST['first_name']
        user.first_name = first_name
        user.save()
    if 'last_name' in request.POST:
        last_name = request.POST['last_name']
        user.last_name = last_name
        user.save()
    if 'email' in request.POST:
        email = request.POST['email']
        user.email = email
        user.save()
    order_entry = Order.objects.filter(profile=profile).filter(status='COMPLETED').order_by('-id')[:5]
    for i in order_entry:
        entries = i.order.all()
        amount = sum(j.count for j in entries)
        i.amount = amount
        count = sum(k.product.price * k.count for k in entries)
        i.count = count
        i.save()
    context = {'first_name': first_name, 'last_name': last_name, 'email': email, 'order': order_entry}
    return render(request, 'shop/account.html', context)


@login_required(redirect_field_name='login')
def order_history(request):
    profile = Profile.objects.get(user=request.user)
    order = Order.objects.filter(profile=profile).filter(status='COMPLETED').order_by('-id')[:5]
    contact_list = Order.objects.filter(profile=profile).filter(status='COMPLETED').order_by('-id')[:5]
    paginator = Paginator(contact_list, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    for i in page_obj:
        entries = i.order.all()
        i.entries = entries
        count = sum(k.product.price * k.count for k in entries)
        i.count = count
        amount = sum(j.count for j in entries)
        i.amount = amount
    context = {'order': order, "page_obj": page_obj}
    return render(request, 'shop/order_history.html', context)

# def products_view(request, ):
#     contact_list = Product.objects.all()
#     paginator = Paginator(contact_list, 5)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)
#     context = {'products': Product.objects.all(), "page_obj": page_obj}
#     return render(request, 'shop/products.html', context)


@login_required(redirect_field_name='login')
def repeat_order(request):
    if request.method == 'POST':

        profile = Profile.objects.get(user=request.user)
        OrderEntry.objects.filter(order=profile.shopping_cart).delete()

        id = request.POST['new_id']
        order = Order.objects.get(id=id)
        entry = OrderEntry.objects.filter(order=order)

        for i in entry:
            try:
                order_entry = OrderEntry.objects.get(order=profile.shopping_cart, product=i.product)
                order_entry.count = i.count
                order_entry.save()
            except OrderEntry.DoesNotExist:
                order_entry = OrderEntry.objects.create(order=profile.shopping_cart, product=i.product)
                order_entry.count = i.count
                order_entry.save()

        t = 0
        for i in OrderEntry.objects.filter(order=profile.shopping_cart):
            t += i.product.price * i.count

    return redirect('shop:shopping_cart')

shop/templates/shop/account.html
{% extends 'shop/base.html' %}
{% block body %}
<br>
<p>Имя: <form action="{% url 'shop:account' %}" method="post">
    {% csrf_token %}
    <input type="text" name='first_name' value={{first_name}}>
    <input type="submit" value="update" class="btn btn-danger"/>
    <input type="hidden" name="user" value="{{user}}"/>
</form>
</p>
<p>Фамилия:
<form action="{% url 'shop:account' %}" method="post">
    {% csrf_token %}
    <input type="text" name='last_name' value={{last_name}}>
    <input type="submit" value="update" class="btn btn-danger"/>
    <input type="hidden" name="user" value="{{user}}"/>
</form>
</p>
<p>Электронная почта:
<form action="{% url 'shop:account' %}" method="post">
    {% csrf_token %}
    <input type="text" name='email' value={{email}}>
    <input type="submit" value="update" class="btn btn-danger"/>
    <input type="hidden" name="user" value="{{user}}"/>
</form>
</p>
<legend>Последние 5 заказов:</legend><br>
{% for order in order %}
Status: {{order.status}}  Total price: {{order.count}}$ Count: {{order.amount}}<br>
{% endfor %}
        <li><a href="{% url 'shop:order_history'%}">История заказов</a></li>
{% endblock %}

shop/templates/shop/base.html
<!doctype html>
<html lang="en">
<head>
    <ul>
        <li><a href="{% url 'shop:products_view'%}">Все продукты</a></li>
        <li><a href="{% url 'shop:all_categories' %}">Категории</a></li>
        <li><a href="{% url 'shop:main'%}">Главная</a></li>
        {% if not user.is_authenticated%}
        <li><a href="{% url 'shop:register'%}">Зарегистрироваться</a></li>
        {% endif %}
        {% if user.is_authenticated%}
        <li><a href="{% url 'shop:account'%}">Личный аккаунт</a></li>
        <li><a href="{% url 'shop:shopping_cart'%}">Моя корзина</a></li>
        {% endif %}
    </ul>
</head>
<body>
<div class="hstack gap-3">
    {% if user.is_authenticated %}
    <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-danger"/>
    </form>
    {% else %}
    <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
    {% endif %}
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div>{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>
{% endif %}

{% block body %} Тут что-то должно быть но я ничего не придумал(Главная){% endblock %}
</body>
</html>

shop/templates/shop/categories.html
{% extends 'shop/base.html' %}

{% block body %}
{% if category %}
<h1>Category:</h1>
    {% for category in category %}
        <legend><h2><li><a href="{% url 'shop:all_of_category' category.id %}">{{ category.name }}</a></li></h2></legend>
    {%endfor%}
{% endif %}
{% endblock %}

shop/templates/shop/category.html
{% extends 'shop/base.html' %}

{% block body %}
{% if category %}
    <h2><legend>Category:{{category.name}}</legend></h2><br>
    {% for product in category.products.all %}
<li><a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a></li>
    {%endfor%}
{% endif %}
{% endblock %}

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}

{% block body %}
{% if product %}
    <legend><h1>{{product.name}}</h1></legend><br>
    <h2>{{product.description}}</h2>
    <h2>{{product.price}}$</h2>
    <h2>Category:<a href="{% url 'shop:all_of_category' product.category.id%}">{{product.category}}</a></h2>
        {% if user.is_authenticated %}
            <form action="{% url 'shop:add_to_cart' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{product.id}}"/>
                <input type="submit" value="add_to_cart" class="btn btn-danger"/>
            </form>
        {% endif%}
{% endif %}
{% endblock %}

shop/templates/shop/new_base.html
{% load static %}


<div class="navbar">
    <a href="#home">Главная</a>
    <a href="#news">Новости</a>
    <div class="dropdown">
        <button class="dropbtn">Выпадающее
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <a href="#">Ссылка 1</a>
            <a href="#">Ссылка 2</a>
            <a href="#">Ссылка 3</a>
            <link rel="stylesheet" type="text/css" href="{% static 'stylesheet.css' %}">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>

shop/templates/shop/order_history.html
{% extends 'shop/base.html' %}
{% block body %}

{% for order in page_obj %}
    <br>
    Заказ номер: {{order.id}} <br>
    {% for entries in order.entries %}
        <a href="{% url 'shop:product_detail' entries.product.id %}">{{entries}}</a>---{{entries.product.price}}$---{{entries.count}}<br>
    {% endfor %}
    <b>Total:</b> {{order.count}}$<br>
    <form action="{% url 'shop:repeat_order' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Повторить заказ" class="btn btn-danger"/>
        <input type="hidden" name="new_id" value="{{order.id}}"/>
        <br>
        </form>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block body %}

<h1>Products:</h1>
{% for product in page_obj %}
<li><a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a></li><br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}{{ product.name|upper }}
    </span>
</div>

{% endblock %}

shop/templates/shop/register.html
<h3>Register</h3>

<form method="POST" action="">
    {% csrf_token %}
    {{form.username.label}}
    {{form.username}}<br>

    {{form.password1.label}}
    {{form.password1}}<br>

    {{form.password2.label}}
    {{form.password2}}<br>

    <input type="submit" name="Create User">
    <li><a href="{% url 'login'%}">Уже есть аккаунт </a></li>
    {%for m in messages%}
    {{m.label}}
    {%endfor%}
</form>

shop/templates/shop/shopping_cart.html
{% extends 'shop/base.html' %}

{% block body %}
{% for order in order_entry %}
<br>
<br>
<li><a href="{% url 'shop:product_detail' order.product.id %}">{{ order }}--{{order.total}}$--{{order.count}}</a></li>
<p>
<form action="{% url 'shop:update_count' %}" method="post">
    {% csrf_token %}
    <input type="number" name='new' value="{{order.count}}"/>
    <input type="submit" value="update" class="btn btn-danger"/>
    <input type="hidden" name="id" value="{{order.id}}"/>
</form>
</p>

<form action="{% url 'shop:clear_concrete_order' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="delete" class="btn btn-danger"/>
    <input type="hidden" name="id" value="{{order.product.id}}"/>
</form><br>
{% endfor %}
<br>
<br>
<form action="{% url 'shop:clear_order' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="clear order" class="btn btn-danger"/>
</form>
Total cost: {{total}}$
<br>
<br>
<br>
<form action="{% url 'shop:make_order' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="make order" class="btn btn-danger"/>
    <input type="hidden" name="status" value="{{order.status}}"/>
</form>
{% endblock %}

shop/templates/shop/success_order.html
{% extends 'shop/base.html' %}


{%block body%}
<p style=»text-align: center;»> Заказ успешно оформлен </p>
<p style=»text-align: center;»>Спасибо за сотрудниччество</p>
{% endblock %}